name: test

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
env:
  go-version: 1.19
jobs:
  golang-lint:
    name: Golang lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Install Go ${{ env.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46
          args: --timeout 5m0s
  build-and-test:
    needs: [golang-lint]
    runs-on: ubuntu-latest
    name: build-test-${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Golang env
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
          cache: true
      - name: Test
        run: go test -v ./...
#      - name: Build
#        run: make build -j8
